AWSTemplateFormatVersion: "2010-09-09"
Description: "CloudFormation IaC --- Private Route 53 DNS Record for a given EC2 Instance"

################################################################################
#
# Decision Trees: none
#
################################################################################


################################################################################
#
# Metadata (optional)
# provide details about the template
#
# See: https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/metadata-section-structure.html
#
################################################################################

Metadata:
  AWS::CloudFormation::Interface:
    ParameterGroups:
    - Label:
        default: "DNS Record configuration"
      Parameters:
      - DnsName
      - HostedZoneName
      - Target
      - TimeToLive
      - Type
    - Label:
        default: "Remote DNS Record configuration (optional)"
      Parameters:
      - ServiceToken


################################################################################
#
# Parameters (optional)
# Passes values into templates when creating a stack
#
# See: http://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/parameters-section-structure.html
#
################################################################################

Parameters:
  #=======================================
  # DNS Record configuration
  #=======================================

  DnsName:
    Description: "The part of the domain that identifies the Instance (must not include the Hosted Zones name; examples: \"assets-dev-author-1\" or \"sites-prod-publish-3\")."
    Type: String

  HostedZoneName:
    Description: "The name of the domain for the Hosted Zone where the Record Sets will be added (example: \"my-project.example.com\")."
    Type: String

  Target:
    Description: "The target for this DNS record. The value must correspond with the value that you specified for the Type property."
    Type: String

  TimeToLive:
    Description: "The private DNS Records cache time to live (TTL), in seconds."
    Type: Number
    Default: 300

  Type:
    Description: "The DNS record type (currently supported values for are: \"A\" and \"CNAME\")"
    Type: String
    AllowedValues: [ "A", "CNAME" ]
    Default: "A"

  #=======================================
  # Remote DNS Record configuration (optional)
  #=======================================

  ServiceToken:
    Description: "The SNS Topic ARN or Lambda function ARN that was provided to access the service that manages remote DNS Records (only required if DNS Records are managed in a different account; must be from the same region as this stack). This feature can be enabled by involving the \"remote-dns-management\" template."
    Type: String
    Default: ""


################################################################################
#
# Conditions (optional)
# Includes statements that define when a resource is created or when a property is defined
#
# See: http://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/conditions-section-structure.html
#
################################################################################

Conditions:

  # If no Service Token has been provided, the DNS Record will be managed in this account
  CreateLocalDnsRecord: !Equals [ !Ref ServiceToken, "" ]

  # If a Service Token has been provided, the DNS Records will be managed in a remote account
  CreateRemoteDnsRecord: !Not
    - !Condition CreateLocalDnsRecord


################################################################################
#
# Resources (required)
# Declares the AWS resources that you want to include in the stack
#
# See: http://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/resources-section-structure.html
#
################################################################################

Resources:
  #=======================================
  # Local DNS Record
  #=======================================

  LocalDnsRecord:
    Condition: CreateLocalDnsRecord
    Type: AWS::Route53::RecordSet
    Properties:
      HostedZoneName: !Sub "${HostedZoneName}."
      Name: !Sub "${DnsName}.${HostedZoneName}"
      ResourceRecords:
      - !Ref Target
      TTL: !Ref TimeToLive
      Type: !Ref Type

  #=======================================
  # Remotely managed DNS Record
  #=======================================

  RemoteDnsRecord:
    Condition: CreateRemoteDnsRecord
    Type: Custom::RemoteDnsRecord
    Properties:
      # The name of the record that we want to create, update, or delete, including the Hosted Zone name (example: "foobar.example.com")
      Name: !Sub "${DnsName}.${HostedZoneName}"
      # The SNS Topic ARN or Lambda function ARN that was provided to access the service that manages remote DNS Records. The service token must be from the same region in which you are creating this stack.
      ServiceToken: !Ref ServiceToken
      # The current or new DNS record value (in this case the IP)
      Target: !Ref Target
      # The DNS record type (currently supported values for are: "A" and "CNAME")
      Type: !Ref Type
      # The private DNS Records cache time to live (TTL), in seconds.
      TTL: !Ref TimeToLive
